# Generated by Django 2.2 on 2020-11-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0003_company_sic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='sic',
        ),
    ]
