# Generated by Django 2.2 on 2020-11-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0004_remove_company_sic'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sic',
            field=models.CharField(db_index=True, default='a', max_length=1024),
            preserve_default=False,
        ),
    ]
