# Generated by Django 2.2 on 2021-01-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0005_company_sic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=64, null=True)),
                ('start_index', models.IntegerField(db_index=True)),
                ('end_index', models.IntegerField(db_index=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openedgar.Filing')),
            ],
        ),
    ]
