# Generated by Django 2.2 on 2021-01-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0006_tablebookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebookmark',
            name='end_index',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
