# Generated by Django 2.2 on 2021-01-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedgar', '0007_auto_20210126_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='notes',
            field=models.TextField(db_index=True, default=False, null=True),
        ),
    ]
